version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-workspace:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /apps/web/src/rust-engine
    schedule:
      interval: weekly
    groups:
      web-wasm-engine:
        patterns:
          - "*"
    open-pull-requests-limit: 5
